### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by engineeringstudent0012** [sparsh-99/Image-Encryption-Decryption#1]
Where are the encrypted and decrypted image are stored?
Can anyone say?
PLEASE HELP!!!

**Comment by sparsh-99** [comment]
Hey @engineeringstudent0012, images stored in the directory in which original files are extracted.

**Comment by sparsh-99** [comment]
> Hey @engineeringstudent0012, images stored in the directory in which original files are extracted.

I hope this helps. For now, I am closing this issue!
If you have any other issues regarding the project, feel free to ping me.

**Comment by engineeringstudent0012** [comment]
> > Hey @engineeringstudent0012, images stored in the directory in which original files are extracted.
> 
> I hope this helps. For now, I am closing this issue!
> If you have any other issues regarding the project, feel free to ping me.

Thank You @sparsh-99  For Your Fast Response.I really appreciate it.
There is no encrypted file in the file location.Can you Please Help Me?
Thank You

![Screenshot (87)_LI](https://user-images.githubusercontent.com/52909024/96106036-6db31d80-0efa-11eb-8a46-7eb466e6db8d.jpg)
![Screenshot (88)](https://user-images.githubusercontent.com/52909024/96106042-70157780-0efa-11eb-8adc-90f0846f5b73.png)
![Screenshot (89)](https://user-images.githubusercontent.com/52909024/96106044-70ae0e00-0efa-11eb-8bc6-8ab350259abe.png)

**Comment by sparsh-99** [comment]
I said encrypted image will be in the project directory, not where the picture is originally there.

**Comment by engineeringstudent0012** [comment]
Thank You For Responding
There is no encrypted image in the project directory.Can you please explain where to look at?
Thank you @sparsh-99 for responding.I am very much grateful for it

**Comment by sparsh-99** [comment]
> Thank You For Responding
> There is no encrypted image in the project directory.Can you please explain where to look at?
> Thank you @sparsh-99 for responding.I am very much grateful for it

I don't know man, where you are lagging from running this project?
